# Generated by Django 2.0.6 on 2020-01-26 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guesses_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='Word must be at least 3 characters long'), django.core.validators.RegexValidator(code='invalid_word_characters', message='Word must only contain capital letters', regex='^[A-Z]$')]),
        ),
    ]
